"""Work dir timelines: written once into `1-cues/`, refined into `2-refined/`.

`refine_cues` used to rewrite the coarse file in place. Two things went
wrong with that, both silent: a refine killed midway left the coarse
timeline damaged -- and that one can only be regenerated by cutting the
episode again, which means downloading the video again -- and two
processes opening the same manifest meant last-writer-wins with nothing
reporting it.

The read side already goes through `cues_to_read()`. These are the
**write** side: `cues` puts the coarse timeline in `1-cues/` and never
touches it again, `refine_cues` puts its result beside it in `2-refined/`.

舊ê平版面（`<work>/cues.json`）愛繼續行會通：遷移工具猶未掃，而且
《開會了》彼爿ê程式直接讀彼个路徑。所以 refine **看輸入ê版面**決定
欲寫佗位——新版面寫 `2-refined/`，平版面照舊就地改寫。
"""
import json
import os
import tempfile
import unittest

from scripts import datadirs
from scripts.news import paths
from scripts.news import refine_cues
from scripts.ocr import cli


MANIFEST = {"video": "/tmp/x.mkv", "region": [0, 722, 1920, 122],
            "cues": [{"index": 1, "start": 1.0, "end": 2.0}]}


class TestStageNamesAreShared(unittest.TestCase):
    """兩爿攏愛用仝一份階段名。

    `scripts.ocr` 刻意無倚靠 `scripts.news`，所以階段名khǹg佇兩爿攏
    用會著ê `datadirs`；`news.paths` 閣 re-export 出去，舊ê呼叫點免改。
    """

    def test_the_stage_names_live_in_the_shared_module(self):
        self.assertEqual(datadirs.COARSE_STAGE, "1-cues")
        self.assertEqual(datadirs.REFINED_STAGE, "2-refined")

    def test_news_paths_still_exposes_them(self):
        self.assertEqual(paths.COARSE_STAGE, datadirs.COARSE_STAGE)
        self.assertEqual(paths.REFINED_STAGE, datadirs.REFINED_STAGE)


class TestCuesWritesTheCoarseStage(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.work = tmp.name

    def test_the_manifest_lands_in_the_coarse_stage(self):
        path = cli.write_manifest(self.work, MANIFEST)
        self.assertEqual(path, paths.coarse_cues(self.work))
        self.assertTrue(os.path.exists(path))

    def test_nothing_is_written_flat_any_more(self):
        cli.write_manifest(self.work, MANIFEST)
        self.assertFalse(os.path.exists(os.path.join(self.work, "cues.json")))

    def test_it_makes_the_stage_folder(self):
        cli.write_manifest(self.work, MANIFEST)
        self.assertTrue(os.path.isdir(
            os.path.join(self.work, datadirs.COARSE_STAGE)))

    def test_what_it_wrote_reads_back(self):
        path = cli.write_manifest(self.work, MANIFEST)
        with open(path, encoding="utf-8") as handle:
            self.assertEqual(json.load(handle)["cues"], MANIFEST["cues"])


class TestRefineWritesBesideTheCoarseOne(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.work = tmp.name

    def _coarse(self):
        path = paths.coarse_cues(self.work)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(MANIFEST, handle, ensure_ascii=False)
        return path

    def _flat(self):
        path = os.path.join(self.work, "cues.json")
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(MANIFEST, handle, ensure_ascii=False)
        return path

    def test_a_staged_input_is_refined_into_the_refined_stage(self):
        self.assertEqual(refine_cues.refined_target(self._coarse()),
                         paths.refined_cues(self.work))

    def test_a_flat_input_is_still_refined_in_place(self):
        """遷移猶未掃ê work dir，佮《開會了》彼爿，攏猶是平ê。"""
        flat = self._flat()
        self.assertEqual(refine_cues.refined_target(flat), flat)

    def test_writing_leaves_the_coarse_timeline_byte_identical(self):
        """粗切彼份寫一擺就唯讀——refine 死佇半路嘛袂kā伊拍歹。"""
        coarse = self._coarse()
        with open(coarse, "rb") as handle:
            before = handle.read()
        refine_cues.write_refined(coarse, dict(MANIFEST, refined=True))
        with open(coarse, "rb") as handle:
            self.assertEqual(handle.read(), before)

    def test_the_refined_timeline_is_where_the_reader_looks(self):
        coarse = self._coarse()
        refine_cues.write_refined(coarse, dict(MANIFEST, refined=True))
        self.assertEqual(paths.cues_to_read(self.work),
                         paths.refined_cues(self.work))

    def test_writing_a_flat_input_updates_that_same_file(self):
        flat = self._flat()
        refine_cues.write_refined(flat, dict(MANIFEST, refined=True))
        with open(flat, encoding="utf-8") as handle:
            self.assertTrue(json.load(handle)["refined"])
        self.assertFalse(os.path.exists(paths.refined_cues(self.work)))


if __name__ == "__main__":
    unittest.main()
