#!/usr/bin/env python3
"""Where data may live, and the guards that keep arguments inside it.

Split out of `scripts.news.paths` so both sides can use it: `scripts/ocr/`
is a reusable engine that deliberately does not depend on `scripts/news/`
(the news orchestration), and inverting that just to validate a path would
have been the wrong trade. What lives here is repo layout plus argument
validation -- facts neither side owns -- plus the two things both corpora
must agree on about Kari-SRT itself: what a stored timeline keeps, and how
the stages contain one another. Corpus-specific paths (the stage folders)
stay in `scripts.news.paths`.
"""
import os
import re
import tempfile
from scripts.errors import PipelineError

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Everything regenerable lives under kithann/; everything canonical under
# Kari-SRT/ (the data submodule).
KITHANN = os.path.join(ROOT, "kithann")
KARI = os.path.join(ROOT, "Kari-SRT")

# The only places a path-shaped CLI argument may legitimately point.
# Deliberately NOT the whole repo -- scripts/ and openspec/ are code and
# specs, not data, and nothing should be reading or writing episodes there.
# The temp dir is in because rebuild and asrmt synthesise work dirs there;
# it is read from tempfile rather than hard-coded so TMPDIR is honoured.
ALLOWED_ROOTS = (KITHANN, KARI, tempfile.gettempdir())


_PATH_COMPONENTS = re.compile(r"[/\\]|\.\.")


def check_name(name, kind="name"):
    """Refuse a name-like CLI argument that carries path components.

    Work dirs and store files are all built as base folder + name; a name
    holding a separator or ".." escapes the base and turns a mistyped (or
    injected) argument into an arbitrary read or write. Validate at the
    entry point, before the name reaches any os.path.join.

    The stripped form is built first and then compared, rather than the
    stripped form being returned: a name that needed stripping stops the
    run. Silently rewriting one would be worse than the typo it came from
    -- 節目目錄是人維護ê，一个恬恬改好ê名會當做本底就按呢寫入 store。
    """
    # 節目目錄彼格空ê時提著ê就是空值；彼是「無名」，毋是「名帶路徑
    # 成分」，訊息愛講對才揣會著問題。
    if not name:
        raise PipelineError("%s 無值" % kind)
    cleaned = _PATH_COMPONENTS.sub("", name)
    if cleaned != name or name == ".":
        raise PipelineError("%s %r 帶路徑成分，拒絕" % (kind, name))
    return cleaned


def check_under(path, kind="path", roots=None):
    """Refuse a path argument that lands outside the data folders.

    Guards against a mistyped (or injected) path argument turning a tool
    that edits one episode into one that edits something else entirely --
    `refine_cues` rewrites cues.json in place, so a wrong target destroys
    a timeline. Compares the realpath, so `..` and symlinks cannot walk
    out, and the base always carries a trailing separator: without it
    "/x/kithann-secret" reads as being inside "/x/kithann".

    Returns `path` unchanged (not the resolved form) so call sites keep
    writing exactly the path the caller named.
    """
    resolved = os.path.realpath(path)
    for base in (roots or ALLOWED_ROOTS):
        base = os.path.realpath(base)
        if resolved == base or resolved.startswith(base + os.sep):
            return path
    raise PipelineError(
        "%s %r 毋佇資料資料夾內底（准的是 kithann/、Kari-SRT/、暫存目錄）"
        % (kind, path))


# A work dir keeps its cue timeline in numbered stage folders, the same way
# the store does: the number is the production order. The names live here
# rather than in `scripts.news.paths` because the ocr engine writes the
# coarse one and deliberately does not depend on that package -- two copies
# of the string is a thing that has to be kept in step, and the symptom of
# missing one is a work dir whose timeline nothing can find.
#
# The split exists because refine used to rewrite the coarse file in place.
# Two things went wrong with that, both silent:
#
#   * a refine killed midway left the coarse timeline damaged -- and that
#     one can only be regenerated by cutting the episode again, which means
#     downloading the video again;
#   * two processes opening the same manifest (a refine still running while
#     something re-cut the same episode) meant last-writer-wins, with
#     nothing anywhere reporting it.
#
# With the stages separated the coarse file is written once and never
# touched again, so a failed refine costs only the refinement.
# 使用者裁定 2026-08-31.
COARSE_STAGE = "1-cues"
REFINED_STAGE = "2-refined"


def coarse_cues(work):
    """The timeline `cues` wrote: 0.2s grid, written once, then read-only."""
    return os.path.join(work, COARSE_STAGE, "cues.json")


def refined_cues(work):
    """The timeline `refine_cues` wrote: boundaries re-read at 25fps."""
    return os.path.join(work, REFINED_STAGE, "cues.json")


# What a work dir's timeline records about *this machine* and the store has
# no use for. `video` is the staged copy's absolute path -- the folder it
# names is gitignored and gone on any other machine, so carrying it into
# Kari-SRT would bind the delivered data to one checkout: the same episode
# re-published elsewhere would differ by that one line. Where the source
# actually lives is the catalogue's 原始影片檔案位置, relative to the
# corpus root -- 節目目錄彼欄本底就規定愛相對路徑，時間軸這欄無人顧著。
MACHINE_LOCAL_KEYS = ("video",)


def store_timeline(manifest):
    """A work dir's timeline as Kari-SRT keeps it.

    Both corpora publish timelines and must agree to the byte, so the rule
    lives here rather than in either publish.
    """
    kept = {}
    for key in manifest:
        if key not in MACHINE_LOCAL_KEYS:
            kept[key] = manifest[key]
    return kept


def stage_problems(stages):
    """Names a downstream stage claims that no upstream stage has.

    `stages` is [(label, {name…})…], upstream first. Each stage's names must
    be a subset of the one before it -- compared pairwise, not against every
    earlier stage, because the chain is transitive and comparing against all
    of them reports the same name once per layer.

    Upstream running ahead is the normal state, not a defect: each stage
    enters Kari-SRT on its own as soon as it is done for that episode, so
    "1-cues has 75 and 3-srt has 40" means forty are read and thirty-five
    are not. The other direction cannot be explained that way -- a
    deliverable whose inputs are not in the store is one nothing can rebuild,
    and that is what `rebuild --verify` exists to catch.

    Every missing name is reported, not just the first: a person fixing this
    wants the list, and stopping at one turns a single pass into several.
    """
    problems = []
    for index in range(1, len(stages)):
        label, names = stages[index]
        above_label, above = stages[index - 1]
        for name in sorted(names - above):
            problems.append("%s 有 %s，%s 無" % (label, name, above_label))
    return problems


def cues_to_read(work):
    """The best timeline this work dir has, or None if it has none.

    Every reader goes through here rather than naming a stage, so "refined
    if there is one, coarse otherwise" is decided once. A part-finished
    batch is the normal state, so an episode that is cut but not yet
    refined still assembles -- with 0.2s boundaries, which the report says.

    The flat `<work>/cues.json` of the pre-split layout used to be read
    here too, last, as a leftover rather than a source of truth: the split
    landed while another line was midway through a seven-hour cutting
    batch that kept producing the old shape. `migrate_workdirs` has swept
    them (75 here, 40 in 開會了, none left either side), so the arm is
    gone -- keeping it would mean a stray flat file gets read silently,
    with nothing saying where it came from.
    """
    for path in (refined_cues(work), coarse_cues(work)):
        if os.path.exists(path):
            return path
    return None
